import { InvoiceData, PaymentDetails } from "./interfaces/interfaces";

export const invoiceTermsOptions = ["None", "Custom", "On Receipt", "Next Day", "2 Days","3 Days","4 Days","5 Days","6 Days","7 Days","10 Days","14 Days","21 Days","30 Days","45 Days","60 Days","90 Days","120 Days","180 Days","365 Days"] as const
export type InvoiceTerms = typeof invoiceTermsOptions[number]

export const taxCategoryOptions = ["On Total", "Deducted", "Per Item", "None"] as const
export type TaxCategory = typeof taxCategoryOptions[number]

export const discountCategoryOptions = ["None", "Percent", "Flat Amount"] as const
export type DiscountCategory = typeof discountCategoryOptions[number]

export enum PlanStatus {
  MONTHLY,
  ANNUAL
}

export const EMAIL_REGEX = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,63}$/
export const MOBILE_NUMBER_REGEX = /^(?:\+1\s?)?(?:\(?\d{3}\)?[\s.-]?)?\d{3}[\s.-]?\d{4}$/
export const PASSWORD_REGEX = /^.{8,}$/

export const currencies = [
  { name: "USD", symbol: "$" },
  { name: "EUR", symbol: "€" },
  { name: "CAD", symbol: "C$" },
  { name: "AED", symbol: "د.إ" },
  { name: "AOA", symbol: "Kz" },
  { name: "ARS", symbol: "$" },
  { name: "AUD", symbol: "A$" },
  { name: "BBD", symbol: "Bds$" },
  { name: "BDT", symbol: "৳" },
  { name: "BHD", symbol: ".د.ب" },
  { name: "BMD", symbol: "$" },
  { name: "BND", symbol: "B$" },
  { name: "BRL", symbol: "R$" },
  { name: "BSD", symbol: "B$" },
  { name: "BWP", symbol: "P" },
  { name: "BZD", symbol: "BZ$" },
  { name: "CDF", symbol: "FC" },
  { name: "CHF", symbol: "CHF" },
  { name: "CLP", symbol: "$" },
  { name: "CNY", symbol: "¥" },
  { name: "COP", symbol: "$" },
  { name: "CZK", symbol: "Kč" },
  { name: "DKK", symbol: "kr" },
  { name: "DZD", symbol: "دج" },
  { name: "EGP", symbol: "£" },
  { name: "ETB", symbol: "Br" },
  { name: "FJD", symbol: "FJ$" },
  { name: "GHS", symbol: "₵" },
  { name: "GBP", symbol: "£" },
  { name: "HKD", symbol: "HK$" },
  { name: "HUF", symbol: "Ft" },
  { name: "IDR", symbol: "Rp" },
  { name: "ILS", symbol: "₪" },
  { name: "INR", symbol: "₹" },
  { name: "JPY", symbol: "¥" },
  { name: "KES", symbol: "Sh" },
  { name: "KRW", symbol: "₩" },
  { name: "KWD", symbol: "د.ك" },
  { name: "LKR", symbol: "Rs" },
  { name: "MAD", symbol: "د.م." },
  { name: "MUR", symbol: "₨" },
  { name: "MWK", symbol: "MK" },
  { name: "MXN", symbol: "$" },
  { name: "MYR", symbol: "RM" },
  { name: "MZN", symbol: "MT" },
  { name: "NGN", symbol: "₦" },
  { name: "NOK", symbol: "kr" },
  { name: "NPR", symbol: "Rs" },
  { name: "NZD", symbol: "NZ$" },
  { name: "OMR", symbol: "﷼" },
  { name: "PEN", symbol: "S/" },
  { name: "PHP", symbol: "₱" },
  { name: "PKR", symbol: "₨" },
  { name: "PLN", symbol: "zł" },
  { name: "QAR", symbol: "﷼" },
  { name: "RON", symbol: "lei" },
  { name: "RUB", symbol: "₽" },
  { name: "SAR", symbol: "﷼" },
  { name: "SCR", symbol: "₨" },
  { name: "SEK", symbol: "kr" },
  { name: "SGD", symbol: "S$" },
  { name: "THB", symbol: "฿" },
  { name: "TND", symbol: "د.ت" },
  { name: "TOP", symbol: "T$" },
  { name: "TRY", symbol: "₺" },
  { name: "TTD", symbol: "TT$" },
  { name: "TWD", symbol: "NT$" },
  { name: "TZS", symbol: "Sh" },
  { name: "UGX", symbol: "USh" },
  { name: "UYU", symbol: "$U" },
  { name: "VND", symbol: "₫" },
  { name: "VUV", symbol: "Vt" },
  { name: "WST", symbol: "WS$" },
  { name: "XAF", symbol: "FCFA" },
  { name: "XOF", symbol: "CFA" },
  { name: "XPF", symbol: "₣" },
  { name: "ZAR", symbol: "R" },
  { name: "ZMW", symbol: "ZK" }
];

export const countries = [
  "United States",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini (fmr. Swaziland)",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

export const usStates = [
  { name: "Alabama", abbreviation: "AL" },
  { name: "Alaska", abbreviation: "AK" },
  { name: "Arizona", abbreviation: "AZ" },
  { name: "Arkansas", abbreviation: "AR" },
  { name: "California", abbreviation: "CA" },
  { name: "Colorado", abbreviation: "CO" },
  { name: "Connecticut", abbreviation: "CT" },
  { name: "Delaware", abbreviation: "DE" },
  { name: "Florida", abbreviation: "FL" },
  { name: "Georgia", abbreviation: "GA" },
  { name: "Hawaii", abbreviation: "HI" },
  { name: "Idaho", abbreviation: "ID" },
  { name: "Illinois", abbreviation: "IL" },
  { name: "Indiana", abbreviation: "IN" },
  { name: "Iowa", abbreviation: "IA" },
  { name: "Kansas", abbreviation: "KS" },
  { name: "Kentucky", abbreviation: "KY" },
  { name: "Louisiana", abbreviation: "LA" },
  { name: "Maine", abbreviation: "ME" },
  { name: "Maryland", abbreviation: "MD" },
  { name: "Massachusetts", abbreviation: "MA" },
  { name: "Michigan", abbreviation: "MI" },
  { name: "Minnesota", abbreviation: "MN" },
  { name: "Mississippi", abbreviation: "MS" },
  { name: "Missouri", abbreviation: "MO" },
  { name: "Montana", abbreviation: "MT" },
  { name: "Nebraska", abbreviation: "NE" },
  { name: "Nevada", abbreviation: "NV" },
  { name: "New Hampshire", abbreviation: "NH" },
  { name: "New Jersey", abbreviation: "NJ" },
  { name: "New Mexico", abbreviation: "NM" },
  { name: "New York", abbreviation: "NY" },
  { name: "North Carolina", abbreviation: "NC" },
  { name: "North Dakota", abbreviation: "ND" },
  { name: "Ohio", abbreviation: "OH" },
  { name: "Oklahoma", abbreviation: "OK" },
  { name: "Oregon", abbreviation: "OR" },
  { name: "Pennsylvania", abbreviation: "PA" },
  { name: "Rhode Island", abbreviation: "RI" },
  { name: "South Carolina", abbreviation: "SC" },
  { name: "South Dakota", abbreviation: "SD" },
  { name: "Tennessee", abbreviation: "TN" },
  { name: "Texas", abbreviation: "TX" },
  { name: "Utah", abbreviation: "UT" },
  { name: "Vermont", abbreviation: "VT" },
  { name: "Virginia", abbreviation: "VA" },
  { name: "Washington", abbreviation: "WA" },
  { name: "West Virginia", abbreviation: "WV" },
  { name: "Wisconsin", abbreviation: "WI" },
  { name: "Wyoming", abbreviation: "WY" },

  // Territories
  { name: "American Samoa", abbreviation: "AS" },
  { name: "Guam", abbreviation: "GU" },
  { name: "Northern Mariana Islands", abbreviation: "MP" },
  { name: "Puerto Rico", abbreviation: "PR" },
  { name: "U.S. Virgin Islands", abbreviation: "VI" }
];

export const defaultInvoiceData: InvoiceData = {
  invoiceId: "",
  invoiceTitle: "",
  fromName: "",
  fromEmail: "",
  fromAddress: "",
  fromPhone: "",
  fromBusiness: "",
  billToName: "",
  billToEmail: "",
  billToAddress: "",
  billToPhone: "",
  billToMobile: "",
  billToFax: "",
  invoiceNumber: "",
  date: new Date().toISOString().split("T")[0],
  terms: "On Receipt" as InvoiceTerms,
  lineItems: [],
  subtotal: 0,
  tax: 0,
  total: 0,
  balance: 0,
  signatureUrl: "",
  notes: ""
};

export const defaultPaymentDetails: PaymentDetails = {
  firstName: "",
  lastName: "",
  email: "",
  streetName: "",
  city: "",
  state: "",
  country: "United States",
  zip: "",
  billingAddress: "",
  billingName: "",
  cardNumber: "",
  expiryMonth: "",
  expiryYear: ""
}